# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ETF Trend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0      # ⬅ 必须加，否则无法提交修改
        token: ${{ secrets.GITHUB_TOKEN }}   # ⬅ 必须加
    - name: Debug files
      run: ls -R .
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run spider_wered
      env:
          WE_RED_TOKEN: ${{ secrets.WE_RED_TOKEN }}
      run: python spider_wered.py > signal.json
   
    - name: Upload signal.json
      uses: actions/upload-artifact@v4
      with:
        name: signal
        path: signal.json
    - name: Commit signal.json to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
        git add signal.json
    
        # 用 [skip ci] 防止触发 workflow
        git commit -m "Update signal.json [skip ci]" || echo "No changes to commit"
    
        git push      
    - name: Send message to Feishu
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"msg_type\":\"text\",\"content\":{\"text\":\"ETF Trend 执行完成！\"}}" \
          ${{ secrets.FEISHU_ROBOT_WEBHOOK }}